<?php
/**
 * Implements hook_menu().
 */
function get_file_menu() {
    $items['admin/config/services/get_image'] = array(
        'title' => t('Get Images'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('get_file_form'),
        'access arguments' => array('administer users'),
        'file' => 'get_file.image.inc'
      );
      
    return $items;
}
      
function _api_vehicle_data_get_files($photoSrc, $path) {
        
        //duong dan den hinh anh
        
        //$image = 'http://promonet.cbs.com/wmm/download/thumbnails.php?loc=2007/05/01/9171/CBS_Sports_Spectacular_logo07.jpg';
        //$image = 'http://promonet.cbs.com/wmm/download/thumbnails.php?loc=2013/09/24/16120/DR_CHRIS_PET_VET_ChrisBrown.JPG';
        //$image = 'http://promonet.cbs.com/wmm/download/thumbnails.php?loc=2014/03/11/17215/FRIENDS_W_BETTER_LIVES_theme.wav';
        //$image = 'http://promonet.cbs.com/wmm/download/thumbnails.php?loc=2014/02/27/17171/TheMillers_728x90_network.psd';
        $image = 'http://promonet.cbs.com/wmm/download/thumbnails.php?loc=2001/11/02/1830/Monday_11_05.jpg';
              
         
        $username = 'trangc';
        $password = 'nikon';
        /*$context = stream_context_create(array(
            'http' => array(
                'header'  => "Authorization: Basic " . base64_encode("$username:$password")
            )
        ));
        
        $image_data = file_get_contents($url, false, $context);*/
        $opts = array('http' =>
            array(
                //'method'  => 'POST',
                //'header'  => "Content-Type: text/xml\r\n".
                "Authorization: Basic ".base64_encode("$username:$password")."\r\n",
                //'content' => $body,
                //'timeout' => 60
            )
        );
                       
        $context  = stream_context_create($opts);
        
        $image_data = file_get_contents($image, true, $context);
        
        //$image_data = file_get_contents($url, false, $context, -1, 40000);
        //$image = 'http://170.20.116.27/pnet/main/tiein/seriesImage.jpg?action=getImage&seriesId=ys27sm0w750309j5amay6yxobri1i3b2';
        
        //$image = 'http://170.20.116.27/pnet/main/tiein/seriesImage.jpg?action=getImage&seriesId=d1n7sfl7gbdja7d9qfsmlxkdxqmce4vy';
        
        //lay hinh anh
        //$image_data = file_get_contents($image);
        
        
        //lay thong tin ve hinh anh
        $info = pathinfo($image);
        //print_r($info);die();
        if(isset($info['extension'])){
            //lay phan duoi mo rong
            $extension = substr($info['extension'], 0, 3);
            
            //lay ten hinh anh
            $filename =  basename($image,'.'.$info['extension']);
            //$filename = basename($image);
            
            
            //$image_path =  file_stream_wrapper_uri_normalize("public://$path");
          //khai bao bien thu muc(tao thu muc neu chua co), luu y tan cung la /  
          $image_path =  file_stream_wrapper_uri_normalize("public://series_image/");
          
          //tao thu muc chua, luu y permission thu muc la 0775
          file_prepare_directory($image_path, FILE_CREATE_DIRECTORY);
          //$destination = 'public://cust_import_pbt/'; //tao thu muc chua file
          //Prepare the pictures directory.
          //file_prepare_directory($destination, FILE_CREATE_DIRECTORY);
          
          //luu hinh anh vao thu muc va lay thong tin bo vao bien file
          //$file = file_save_data($image_data, "$image_path/$filename.".$extension, FILE_EXISTS_REPLACE);
          //$file = file_save_upload('file_upload', $validators, $destination, FILE_EXISTS_RENAME);
          
          $file = file_save_data($image_data, "$image_path/$filename.".$extension, FILE_EXISTS_RENAME);
          
          return $file;
        }
}

function file_get_contents_secure($url, $username, $password)
{
   $opts = array('http'=>
                 array('method'=>'POST',
                       'header'=>sprintf("Authorization Basic %s\r\n", 
                       base64_encode($username.':'.$password)).
                       "Content-type: application/x-www-form-urlencoded\r\n"
                      )
                );
   $context = stream_context_create($opts);
   $fh = fopen($url, 'r', false, $context);
   ob_start();
   fpassthru($fh);
   fclose($fh);
   $contents = ob_get_contents();
   ob_end_clean();
   return $contents;
}



function get_file_files(){
    $loginUrl = 'http://promonet.cbs.com/home.php'; //action from the login form
    $loginFields = array('username'=>'trangc', 'password'=>'nikon'); //login form field names and values
    $remotePageUrl = 'http://promonet.cbs.com/wmm/download/thumbnails.php?loc=2013/09/19/16103/2_BROKE_GIRLS_logo_backplate.jpg_310.jpg/'; //url of the page you want to save  
    
    $login = getUrl($loginUrl, 'post', $loginFields); //login to the site
    
    $remotePage = getUrl($remotePageUrl); //get the remote page
    print $remotePage;
}

/*function getUrl($url, $method='', $vars='') {
    $ch = curl_init();
    if ($method == 'post') {
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $vars);
    }
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
    curl_setopt($ch, CURLOPT_COOKIEJAR, 'cookies/cookies.txt');
    curl_setopt($ch, CURLOPT_COOKIEFILE, 'cookies/cookies.txt');
    $buffer = curl_exec($ch);
    curl_close($ch);
    return $buffer;
}*/

function getUrl($file_id) {
  $remotePageUrl = "http://promoadmin.cbs.com/wmm/download/files.php?fld=$file_id"; //url of the 
      
  $username = 'trangcao';
  $password = 'trang';
   
  //login form action url
  $url = 'http://promoadmin.cbs.com/index.php'; 
  
  $postinfo = "username=".$username."&password=".$password;
  
  $cookie_file_path = CBS_MODULE_PATH."/cookie.txt";
  
  $ch = curl_init();
  curl_setopt($ch, CURLOPT_HEADER, false);
  curl_setopt($ch, CURLOPT_NOBODY, false);
  curl_setopt($ch, CURLOPT_URL, $url);
  curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
  
  curl_setopt($ch, CURLOPT_COOKIEJAR, $cookie_file_path);
  //set the cookie the site has for certain features, this is optional
  curl_setopt($ch, CURLOPT_COOKIE, "cookiename=0");
  curl_setopt($ch, CURLOPT_USERAGENT,
      "Mozilla/5.0 (Windows; U; Windows NT 5.0; en-US; rv:1.7.12) Gecko/20050915 Firefox/1.0.7");
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch, CURLOPT_REFERER, $_SERVER['REQUEST_URI']);
  curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
  curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 0);
  
  curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
  curl_setopt($ch, CURLOPT_POST, 1);
  curl_setopt($ch, CURLOPT_POSTFIELDS, $postinfo);
  curl_exec($ch);
  
  //page with the content I want to grab
  curl_setopt($ch, CURLOPT_URL, $remotePageUrl);
  //do stuff with the info with DomDocument() etc
  $html = curl_exec($ch);  
  curl_close($ch);
  return $html;
}
